import { languages } from '@/i18n/settings';
import { dir } from 'i18next';

import '@/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/app/providers';
import Header from '@/components/Header';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { language },
}: Readonly<{
  children: React.ReactNode;
  params: {
    language: string;
  };
}>) {
  return (
    <html lang={language} dir={dir(language)}>
      <body className={`${inter.className} max-w-6xl m-auto px-4`}>
        <Providers>
          <Header language={language} />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
